name: flutter_final
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  flutter_map: ^8.1.1
  intl: ^0.20.2 # 添加這一行，使用最新版本
  geolocator: ^14.0.1
  audioplayers: ^6.0.0
  sqflite: ^2.4.2
  webview_flutter: ^4.2.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9
  xml: ^6.4.0
  path_provider: ^2.1.1
  url_launcher: ^6.1.11
  flutter_phoenix: ^1.0.0
  http: ^1.4.0
  gpx: ^2.3.0
  rename_app: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map.jpg
    - assets/flutter.png
    - assets/audios/
    - assets/gpx/